### ISSUE TITLE
Generation of synthetic data

### ISSUE THREAD

**Issue by l0ka** [dvav/clonosGP#1] opened 2021-10-05 12:24 UTC
Hi @dvav, thank you for the nice paper and for sharing the code. I'm interested in the synthetic data generation step, using the `run_models_on_simulated_data.py` python script and I'm not sure I correctly understood how it works (sorry, not very proficient with python). 
I'd like to generate 9 data sets as following:
* Dataset1 = 50 mutations, K=4
* Dataset2 = 50 mutations, K=6 
* Dataset3 = 50 mutations, K=8
* Dataset4 = 100 mutations, K=4
* Dataset1 = 100 mutations, K=6
* Dataset1 = 100 mutations, K=8
* Dataset1 = 150 mutations, K=4
* Dataset1 = 150 mutations, K=6
* Dataset1 = 150 mutations, K=8
with K=number of clusters. Each data set should have 3 samples (e.g. 3 time points such as "primary tumor", "1st relapse" and "2nd relapse"). I modified the script:
```
DATA = [[R, K, M, N, TAU, H2, cln.sim.get_Nsamples(nclusters=K, nmuts=N, nsamples=M, tau=TAU, h2=H2, mean_depth=(40, 40), depths=depths)] 
        for R, K, M, N, TAU, H2 in itr.product([1], [4, 6, 8], [3], [50, 100, 150], [100], [20])]
```
and it seems to be doing what I need. Am I correct? 
Additionally, do you have any suggestion on how I could vary TAU and H2 parameters?

**Comment by dvav** [comment] 2021-10-06 09:00
Hi @l0ka,

Thank you very much for your interest in our work.

 The way you generate the data seems to be correct. In order to run the simulations you do something like this:

`parallel -j9 python run_models_on_simulated_data.py {} ::: {1..9}`

Also, have a look at the file `run_models_on_simulated_data.sh` for an example script to be used on an SGE cluster.

Regarding parameters TAU and H2, the values I use in `run_models_on_simulated_data.py` include the range of values I estimated from the actual data I analysed in the paper. You can use these, or do something similar with your own datasets, i.e. estimate TAU and H2 on your datasets and use the estimated values in your simulated data. 

Just to confirm: have you gone through the tutorial and confirmed that the software is properly installed and works on your system?

**Comment by l0ka** [comment] 2021-10-06 09:08
Thank you very much @dvav. Estimating the parameters is actually a very good idea, then I can compare the estimates on my data set with yours from the paper.
Regarding the tutorial, yes, I followed the long one (https://github.com/dvav/clonosGP/blob/master/tutorial.ipynb) and everything's working as expected!

**Comment by dvav** [comment] 2021-10-06 09:14
OK, that's great and good luck with your research! I 'll now close this issue.

**Closed as completed by dvav** 2021-10-06 09:14 UTC
